// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskTaskerAPI.DAL.Context;

#nullable disable

namespace TaskTaskerAPI.Migrations
{
    [DbContext(typeof(TaskTaskerContext))]
    [Migration("20260822032225_AddAdminUser")]
    partial class AddAdminUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskTaskerAPI.DAL.Entities.Achievement", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("days")
                        .HasColumnType("integer");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("task_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("task_id");

                    b.ToTable("Achievement");
                });

            modelBuilder.Entity("TaskTaskerAPI.DAL.Entities.AdminUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id");

                    b.ToTable("AdminUser");
                });

            modelBuilder.Entity("TaskTaskerAPI.DAL.Entities.Assignment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("member_id")
                        .HasColumnType("integer");

                    b.Property<int>("status_id")
                        .HasColumnType("integer");

                    b.Property<int>("task_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("member_id");

                    b.HasIndex("status_id");

                    b.HasIndex("task_id");

                    b.ToTable("Assignment");
                });

            modelBuilder.Entity("TaskTaskerAPI.DAL.Entities.Attainment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("achievement_id")
                        .HasColumnType("integer");

                    b.Property<int>("member_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("achievement_id");

                    b.HasIndex("member_id");

                    b.ToTable("Attainment");
                });

            modelBuilder.Entity("TaskTaskerAPI.DAL.Entities.Home", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("id");

                    b.ToTable("Home");
                });

            modelBuilder.Entity("TaskTaskerAPI.DAL.Entities.Member", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("home_id")
                        .HasColumnType("integer");

                    b.Property<int>("person_id")
                        .HasColumnType("integer");

                    b.Property<int>("role_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("home_id");

                    b.HasIndex("person_id");

                    b.HasIndex("role_id");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("TaskTaskerAPI.DAL.Entities.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("TaskTaskerAPI.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_revoked")
                        .HasColumnType("boolean");

                    b.Property<int>("person_id")
                        .HasColumnType("integer");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("person_id");

                    b.HasIndex("token");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("TaskTaskerAPI.DAL.Entities.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("TaskTaskerAPI.DAL.Entities.Status", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("TaskTaskerAPI.DAL.Entities.Task", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("id");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("TaskTaskerAPI.DAL.Entities.Achievement", b =>
                {
                    b.HasOne("TaskTaskerAPI.DAL.Entities.Task", "task")
                        .WithMany()
                        .HasForeignKey("task_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("task");
                });

            modelBuilder.Entity("TaskTaskerAPI.DAL.Entities.Assignment", b =>
                {
                    b.HasOne("TaskTaskerAPI.DAL.Entities.Member", "member")
                        .WithMany()
                        .HasForeignKey("member_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskTaskerAPI.DAL.Entities.Status", "status")
                        .WithMany()
                        .HasForeignKey("status_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskTaskerAPI.DAL.Entities.Task", "task")
                        .WithMany()
                        .HasForeignKey("task_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("member");

                    b.Navigation("status");

                    b.Navigation("task");
                });

            modelBuilder.Entity("TaskTaskerAPI.DAL.Entities.Attainment", b =>
                {
                    b.HasOne("TaskTaskerAPI.DAL.Entities.Achievement", "achievement")
                        .WithMany()
                        .HasForeignKey("achievement_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskTaskerAPI.DAL.Entities.Member", "member")
                        .WithMany()
                        .HasForeignKey("member_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("achievement");

                    b.Navigation("member");
                });

            modelBuilder.Entity("TaskTaskerAPI.DAL.Entities.Member", b =>
                {
                    b.HasOne("TaskTaskerAPI.DAL.Entities.Home", "home")
                        .WithMany()
                        .HasForeignKey("home_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskTaskerAPI.DAL.Entities.Person", "person")
                        .WithMany()
                        .HasForeignKey("person_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskTaskerAPI.DAL.Entities.Role", "role")
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("home");

                    b.Navigation("person");

                    b.Navigation("role");
                });

            modelBuilder.Entity("TaskTaskerAPI.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("TaskTaskerAPI.DAL.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("person_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
